<?php

add_action('acf/include_fields', function () {
	if (!function_exists('acf_add_local_field_group')) {
		return;
	}

	acf_add_local_field_group(array(
		'key' => 'group_6951f1ee5ebf0',
		'title' => 'Article fields',
		'fields' => array(
			array(
				'key' => 'field_695ab01b6404c',
				'label' => 'Подзаголовок',
				'name' => 'subtitle',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_6951f81054002',
				'label' => 'Для педагогов (длинно)',
				'name' => 'for_scientist_long',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6952c71b217e9',
				'label' => 'Для педагогов (кратко)',
				'name' => 'for_scientist_short',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6951f80554001',
				'label' => 'Для родителей (длинно)',
				'name' => 'for_parent_long',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_6951f1ee0de17',
				'label' => 'Для родителей (кратко)',
				'name' => 'for_parent_short',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 1,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'article',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_695db8d315240',
		'title' => 'Автор статьи поля',
		'fields' => array(
			array(
				'key' => 'field_695db8d47402f',
				'label' => 'Фамилия',
				'name' => 'last_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_695db90374030',
				'label' => 'Имя',
				'name' => 'first_name',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_695db93874031',
				'label' => 'Фото',
				'name' => 'photo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'allow_in_bindings' => 0,
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_695db97974032',
				'label' => 'Главная информация',
				'name' => 'bio',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'allow_in_bindings' => 0,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_695db9d474033',
				'label' => 'Описание',
				'name' => 'info',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'article_author',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_6963e16735f95',
		'title' => 'Проект поля',
		'fields' => array(
			array(
				'key' => 'field_6963e169b70e1',
				'label' => 'Краткое описание',
				'name' => 'project_description',
				'aria-label' => '',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'allow_in_bindings' => 0,
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'projects',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'group_69584e787f669',
		'title' => 'Раздел методологии поля',
		'fields' => array(
			array(
				'key' => 'field_69584e7b607bb',
				'label' => 'Цвет',
				'name' => 'color',
				'aria-label' => '',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#FF0000',
				'enable_opacity' => 1,
				'return_format' => 'string',
				'allow_in_bindings' => 0,
				'show_custom_palette' => 0,
				'show_color_wheel' => 1,
				'custom_palette_source' => '',
				'palette_colors' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'methodology_tag',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
		'display_title' => '',
	));
});

add_action('init', function () {
	register_taxonomy('article_author', array(
		0 => 'article',
	), array(
		'labels' => array(
			'name' => 'Авторы статей',
			'singular_name' => 'Автор статьи',
			'menu_name' => 'Авторы статей',
			'all_items' => 'Все Авторы статей',
			'edit_item' => 'Изменить Автор статьи',
			'view_item' => 'Посмотреть Автор статьи',
			'update_item' => 'Обновить Автор статьи',
			'add_new_item' => 'Добавить новое Автор статьи',
			'new_item_name' => 'Новое Автор статьи название',
			'search_items' => 'Поиск Авторы статей',
			'popular_items' => 'Популярные Авторы статей',
			'separate_items_with_commas' => 'Разделять авторы статей запятыми',
			'add_or_remove_items' => 'Добавить или удалить авторы статей',
			'choose_from_most_used' => 'Выберите из наиболее часто используемых авторы статей',
			'not_found' => 'Не найдено авторы статей',
			'no_terms' => 'Нет авторы статей',
			'items_list_navigation' => 'Авторы статей навигация по списку',
			'items_list' => 'Авторы статей список',
			'back_to_items' => '← Перейти к авторы статей',
			'item_link' => 'Cсылка на Автор статьи',
			'item_link_description' => 'Ссылка на автор статьи',
		),
		'description' => 'Авторы статей могут быть выбраны в качестве авторов, также они будут отображаться в секции "Команда"',
		'public' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
		'show_admin_column' => true,
	));

	register_taxonomy('methodology_tag', array(
		0 => 'article',
	), array(
		'labels' => array(
			'name' => 'Разделы методологии',
			'singular_name' => 'Раздел методологии',
			'menu_name' => 'Разделы методологии',
			'all_items' => 'Все Разделы методологии',
			'edit_item' => 'Изменить Раздел методологии',
			'view_item' => 'Посмотреть Раздел методологии',
			'update_item' => 'Обновить Раздел методологии',
			'add_new_item' => 'Добавить новое Раздел методологии',
			'new_item_name' => 'Новое Раздел методологии название',
			'search_items' => 'Поиск Разделы методологии',
			'popular_items' => 'Популярные Разделы методологии',
			'separate_items_with_commas' => 'Разделять разделы методологии запятыми',
			'add_or_remove_items' => 'Добавить или удалить разделы методологии',
			'choose_from_most_used' => 'Выберите из наиболее часто используемых разделы методологии',
			'not_found' => 'Не найдено разделы методологии',
			'no_terms' => 'Нет разделы методологии',
			'items_list_navigation' => 'Разделы методологии навигация по списку',
			'items_list' => 'Разделы методологии список',
			'back_to_items' => '← Перейти к разделы методологии',
			'item_link' => 'Cсылка на Раздел методологии',
			'item_link_description' => 'Ссылка на раздел методологии',
		),
		'public' => true,
		'show_in_menu' => true,
		'show_in_rest' => true,
	));
});

add_action('init', function () {
	register_post_type('article', array(
		'labels' => array(
			'name' => 'Articles',
			'singular_name' => 'Article',
			'menu_name' => 'Article',
			'all_items' => 'Все Article',
			'edit_item' => 'Изменить Article',
			'view_item' => 'Посмотреть Article',
			'view_items' => 'Посмотреть Article',
			'add_new_item' => 'Добавить новое Article',
			'add_new' => 'Добавить новое Article',
			'new_item' => 'Новый Article',
			'parent_item_colon' => 'Родитель Article:',
			'search_items' => 'Поиск Article',
			'not_found' => 'Не найдено article',
			'not_found_in_trash' => 'В корзине не найдено article',
			'archives' => 'Архивы Article',
			'attributes' => 'Атрибуты Article',
			'insert_into_item' => 'Вставить в article',
			'uploaded_to_this_item' => 'Загружено в это article',
			'filter_items_list' => 'Фильтровать список article',
			'filter_by_date' => 'Фильтр article по дате',
			'items_list_navigation' => 'Article навигация по списку',
			'items_list' => 'Article список',
			'item_published' => 'Article опубликовано.',
			'item_published_privately' => 'Article опубликована приватно.',
			'item_reverted_to_draft' => 'Article преобразован в черновик.',
			'item_scheduled' => 'Article запланировано.',
			'item_updated' => 'Article обновлён.',
			'item_link' => 'Cсылка на Article',
			'item_link_description' => 'Ссылка на article.',
		),
		'description' => 'Статьи в 4 режимах просмотра',
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array(
			0 => 'title',
			1 => 'excerpt',
			2 => 'revisions',
			3 => 'thumbnail',
			4 => 'custom-fields',
			5 => 'Подзаголовок',
		),
		'delete_with_user' => false,
	));

	register_post_type('projects', array(
		'labels' => array(
			'name' => 'Проекты',
			'singular_name' => 'Проект',
			'menu_name' => 'Проекты',
			'all_items' => 'Все Проекты',
			'edit_item' => 'Изменить Проект',
			'view_item' => 'Посмотреть Проект',
			'view_items' => 'Посмотреть Проекты',
			'add_new_item' => 'Добавить новое Проект',
			'add_new' => 'Добавить новое Проект',
			'new_item' => 'Новый Проект',
			'parent_item_colon' => 'Родитель Проект:',
			'search_items' => 'Поиск Проекты',
			'not_found' => 'Не найдено проекты',
			'not_found_in_trash' => 'В корзине не найдено проекты',
			'archives' => 'Архивы Проект',
			'attributes' => 'Атрибуты Проект',
			'insert_into_item' => 'Вставить в проект',
			'uploaded_to_this_item' => 'Загружено в это проект',
			'filter_items_list' => 'Фильтровать список проекты',
			'filter_by_date' => 'Фильтр проекты по дате',
			'items_list_navigation' => 'Проекты навигация по списку',
			'items_list' => 'Проекты список',
			'item_published' => 'Проект опубликовано.',
			'item_published_privately' => 'Проект опубликована приватно.',
			'item_reverted_to_draft' => 'Проект преобразован в черновик.',
			'item_scheduled' => 'Проект запланировано.',
			'item_updated' => 'Проект обновлён.',
			'item_link' => 'Cсылка на Проект',
			'item_link_description' => 'Ссылка на проект.',
		),
		'public' => true,
		'show_in_rest' => true,
		'menu_icon' => 'dashicons-admin-post',
		'supports' => array(
			0 => 'title',
			1 => 'editor',
			2 => 'excerpt',
			3 => 'thumbnail',
		),
		'delete_with_user' => false,
	));
});


?>