add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6951f1ee5ebf0',
	'title' => 'Article fields',
	'fields' => array(
		array(
			'key' => 'field_6951f1ee0de17',
			'label' => 'Для родителей (кратко)',
			'name' => 'for_parent_short',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 1,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6951f80554001',
			'label' => 'Для родителей (длинно)',
			'name' => 'for_parent_long',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6951f81054002',
			'label' => 'Для педагогов (длинно)',
			'name' => 'for_scientist_long',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6952c71b217e9',
			'label' => 'Для педагогов (кратко)',
			'name' => 'for_scientist_short',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_69584f0483e02',
			'label' => 'Авторы',
			'name' => 'authors',
			'aria-label' => '',
			'type' => 'user',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => '',
			'return_format' => 'array',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'bidirectional' => 0,
			'bidirectional_target' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'article',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );

	acf_add_local_field_group( array(
	'key' => 'group_69584e787f669',
	'title' => 'Раздел методологии поля',
	'fields' => array(
		array(
			'key' => 'field_69584e7b607bb',
			'label' => 'Цвет',
			'name' => 'color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#FF0000',
			'enable_opacity' => 1,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
			'show_custom_palette' => 0,
			'show_color_wheel' => 1,
			'custom_palette_source' => '',
			'palette_colors' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'taxonomy',
				'operator' => '==',
				'value' => 'methodology_tag',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );

add_action( 'init', function() {
	register_taxonomy( 'methodology_tag', array(
	0 => 'article',
), array(
	'labels' => array(
		'name' => 'Разделы методологии',
		'singular_name' => 'Раздел методологии',
		'menu_name' => 'Разделы методологии',
		'all_items' => 'Все Разделы методологии',
		'edit_item' => 'Изменить Раздел методологии',
		'view_item' => 'Посмотреть Раздел методологии',
		'update_item' => 'Обновить Раздел методологии',
		'add_new_item' => 'Добавить новое Раздел методологии',
		'new_item_name' => 'Новое Раздел методологии название',
		'search_items' => 'Поиск Разделы методологии',
		'popular_items' => 'Популярные Разделы методологии',
		'separate_items_with_commas' => 'Разделять разделы методологии запятыми',
		'add_or_remove_items' => 'Добавить или удалить разделы методологии',
		'choose_from_most_used' => 'Выберите из наиболее часто используемых разделы методологии',
		'not_found' => 'Не найдено разделы методологии',
		'no_terms' => 'Нет разделы методологии',
		'items_list_navigation' => 'Разделы методологии навигация по списку',
		'items_list' => 'Разделы методологии список',
		'back_to_items' => '← Перейти к разделы методологии',
		'item_link' => 'Cсылка на Раздел методологии',
		'item_link_description' => 'Ссылка на раздел методологии',
	),
	'public' => true,
	'show_in_menu' => true,
	'show_in_rest' => true,
) );
} );

add_action( 'init', function() {
	register_post_type( 'article', array(
	'labels' => array(
		'name' => 'Articles',
		'singular_name' => 'Article',
		'menu_name' => 'Article',
		'all_items' => 'Все Article',
		'edit_item' => 'Изменить Article',
		'view_item' => 'Посмотреть Article',
		'view_items' => 'Посмотреть Article',
		'add_new_item' => 'Добавить новое Article',
		'add_new' => 'Добавить новое Article',
		'new_item' => 'Новый Article',
		'parent_item_colon' => 'Родитель Article:',
		'search_items' => 'Поиск Article',
		'not_found' => 'Не найдено article',
		'not_found_in_trash' => 'В корзине не найдено article',
		'archives' => 'Архивы Article',
		'attributes' => 'Атрибуты Article',
		'insert_into_item' => 'Вставить в article',
		'uploaded_to_this_item' => 'Загружено в это article',
		'filter_items_list' => 'Фильтровать список article',
		'filter_by_date' => 'Фильтр article по дате',
		'items_list_navigation' => 'Article навигация по списку',
		'items_list' => 'Article список',
		'item_published' => 'Article опубликовано.',
		'item_published_privately' => 'Article опубликована приватно.',
		'item_reverted_to_draft' => 'Article преобразован в черновик.',
		'item_scheduled' => 'Article запланировано.',
		'item_updated' => 'Article обновлён.',
		'item_link' => 'Cсылка на Article',
		'item_link_description' => 'Ссылка на article.',
	),
	'public' => true,
	'show_in_rest' => true,
	'menu_icon' => 'dashicons-admin-post',
	'supports' => array(
		0 => 'title',
		1 => 'author',
		2 => 'trackbacks',
		3 => 'editor',
		4 => 'excerpt',
		5 => 'revisions',
		6 => 'page-attributes',
		7 => 'thumbnail',
		8 => 'custom-fields',
		9 => 'post-formats',
	),
	'delete_with_user' => false,
) );
} );

