export const initialTags = [
    {
        id: "Agency",
        name: wp.i18n.__("Субъектность", 'childlab'),
        color: "#90b636",
        textOrientation: "horizontal",
        fontSize: 20,
        xPercent: 50.0,
        yPercent: 4,
    },
    {
        id: "Self_regulatory_abilities",
        name: wp.i18n.__("Регуляторные \n способности", 'childlab'),
        color: "#38d37c",
        textOrientation: "horizontal",
        fontSize: 16,
        xPercent: 25,
        yPercent: 18.0,
    },
    {
        id: "Cognitive_abilities",
        name: wp.i18n.__("Познавательные \n способности", 'childlab'),
        color: "#dcc22d",
        textOrientation: "horizontal",
        fontSize: 16,
        xPercent: 76,
        yPercent: 18.0,
    },
    {
        id: "Communicative_abilities",
        name: wp.i18n.__("Коммуникативные \n способности", 'childlab'),
        color: "#db508f",
        textOrientation: "horizontal",
        fontSize: 16,
        xPercent: 50.0,
        yPercent: 27.0,
    },
    {
        id: "Planning",
        name: wp.i18n.__("Планирование", 'childlab'),
        color: "#64af38",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 12,
        yPercent: 10,
    },
    {
        id: "Imagination",
        name: wp.i18n.__("Воображение", 'childlab'),
        color: "#becc1c",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 88,
        yPercent: 10,
    },
    {
        id: "Dialectical_thinking",
        name: wp.i18n.__("Диалектическое \n мышление", 'childlab'),
        color: "#f3c932",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 87,
        yPercent: 27,
    },
    {
        id: "Anticipation",
        name: wp.i18n.__("Предвосхищение", 'childlab'),
        color: "#e99030",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 85,
        yPercent: 35,
    },
    {
        id: "argumentation",
        name: wp.i18n.__("Аргументация", 'childlab'),
        color: "#ea6695",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 76,
        yPercent: 42,
    },
    {
        id: "Decentration",
        name: wp.i18n.__("Децентрация", 'childlab'),
        color: "#D34FB5",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 50.0,
        yPercent: 35,
    },
    {
        id: "Volitional_control",
        name: wp.i18n.__("Произвольность", 'childlab'),
        color: "#49C64F",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 14,
        yPercent: 25,
    },
    {
        id: "moral_reasoning",
        name: wp.i18n.__("Моральные суждения", 'childlab'),
        color: "#B949D4",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 50.0,
        yPercent: 48,
    },
    {
        id: "reflection",
        name: wp.i18n.__("Рефлексия", 'childlab'),
        color: "#9AD04A",
        textOrientation: "horizontal",
        fontSize: 13,
        xPercent: 25,
        yPercent: 42,
    },
    {
        id: "construction",
        name: wp.i18n.__("Конструирование", 'childlab'),
        color: "#6E41D8",
        textOrientation: "vertical",
        fontSize: 16,
        xPercent: 54.5,
        yPercent: 74,
    },
    {
        id: "shared_reading",
        name: wp.i18n.__("Совместное чтение", 'childlab'),
        color: "#4164D9",
        textOrientation: "vertical",
        fontSize: 16,
        xPercent: 50,
        yPercent: 71,
    },
    {
        id: "storytelling",
        name: wp.i18n.__("Сочинительство", 'childlab'),
        color: "#50D4CB",
        textOrientation: "vertical",
        fontSize: 16,
        xPercent: 45.5,
        yPercent: 74,
    },
    {
        id: "experimentation",
        name: wp.i18n.__("Экспериментирование", 'childlab'),
        color: "#42A0CC",
        textOrientation: "vertical",
        fontSize: 16,
        xPercent: 59,
        yPercent: 73,
    },
    {
        id: "game",
        name: wp.i18n.__("    Игра    ", 'childlab'),
        color: "#C1593A",
        textOrientation: "vertical",
        fontSize: 16,
        xPercent: 41,
        yPercent: 74,
    },
    {
        id: "attachment",
        name: wp.i18n.__("Привязанность", 'childlab'),
        color: "#8A6720",
        textOrientation: "horizontal",
        fontSize: 20,
        xPercent: 50.0,
        yPercent: 96,
    },
];

export const initialConnections = [
    {
        source: "Agency",
        target: "Self_regulatory_abilities",
        curveIntensity: 0,
        connectFrom: "bottom",
        connectTo: "right",
        lineWidth: 4,
    },
    {
        source: "Agency",
        target: "Cognitive_abilities",
        curveIntensity: 0,
        connectFrom: "bottom",
        connectTo: "left",
        lineWidth: 4,
    },
    {
        source: "Self_regulatory_abilities",
        target: "Cognitive_abilities",
        curveIntensity: 0,
        connectFrom: "right",
        connectTo: "left",
        lineWidth: 4,
    },
    {
        source: "Self_regulatory_abilities",
        target: "Communicative_abilities",
        curveIntensity: 0,
        connectFrom: "right",
        connectTo: "top",
        lineWidth: 4,
    },
    {
        source: "Cognitive_abilities",
        target: "Communicative_abilities",
        curveIntensity: 0,
        connectFrom: "left",
        connectTo: "top",
        lineWidth: 4,
    },
    {
        source: "Agency",
        target: "Communicative_abilities",
        curveIntensity: 0,
        connectFrom: "bottom",
        connectTo: "top",
        lineWidth: 4,
    },
    {
        source: "Cognitive_abilities",
        target: "Imagination",
        curveIntensity: -0.4,
        connectFrom: "top",
        connectTo: "left",
        lineWidth: 2,
    },
    {
        source: "Planning",
        target: "Self_regulatory_abilities",
        curveIntensity: -0.4,
        connectFrom: "right",
        connectTo: "top",
        lineWidth: 2,
    },
    {
        source: "Dialectical_thinking",
        target: "Cognitive_abilities",
        curveIntensity: -0.3,
        connectFrom: "left",
        connectTo: "bottom",
        shiftTo: -0.05,
        lineWidth: 2,
    },
    {
        source: "Anticipation",
        target: "Cognitive_abilities",
        curveIntensity: -0.2,
        connectFrom: "top",
        shiftFrom: -0.8,
        connectTo: "bottom",
        shiftTo: -0.2,
        lineWidth: 2,
    },
    {
        source: "argumentation",
        target: "Cognitive_abilities",
        curveIntensity: 0.05,
        connectFrom: "top",
        shiftFrom: -0.8,
        connectTo: "bottom",
        shiftTo: -0.3,
        lineWidth: 2,
    },
    {
        source: "Communicative_abilities",
        target: "argumentation",
        curveIntensity: 0.3,
        connectFrom: "bottom",
        shiftFrom: 0.9,
        connectTo: "left",
        lineWidth: 2,
    },
    {
        source: "Communicative_abilities",
        target: "Decentration",
        curveIntensity: 0.2,
        connectFrom: "bottom",
        connectTo: "top",
        lineWidth: 2,
    },
    {
        source: "Self_regulatory_abilities",
        target: "Volitional_control",
        curveIntensity: -0.2,
        connectFrom: "bottom",
        shiftFrom: 0.2,
        connectTo: "right",
        lineWidth: 2,
    },
    {
        source: "moral_reasoning",
        target: "Cognitive_abilities",
        curveIntensity: 0.2,
        connectFrom: "top",
        shiftFrom: 0.6,
        connectTo: "bottom",
        shiftTo: -0.5,
        lineWidth: 2,
    },
    {
        source: "reflection",
        target: "Cognitive_abilities",
        curveIntensity: 0.6,
        connectFrom: "right",
        connectTo: "bottom",
        shiftTo: -0.7,
        lineWidth: 2,
    },
    {
        source: "reflection",
        target: "Self_regulatory_abilities",
        curveIntensity: 0.2,
        connectFrom: "top",
        connectTo: "bottom",
        shiftTo: 0.5,
        lineWidth: 2,
    },
    {
        source: "construction",
        target: "moral_reasoning",
        curveIntensity: -0.05,
        connectFrom: "top",
        shiftFrom: 15,
        connectTo: "bottom",
        shiftTo: 0.6,
        lineWidth: 2,
    },
    {
        source: "experimentation",
        target: "moral_reasoning",
        curveIntensity: -0.07,
        connectFrom: "top",
        shiftFrom: 20,
        connectTo: "bottom",
        shiftTo: 1.1,
        lineWidth: 2,
    },
    {
        source: "moral_reasoning",
        target: "storytelling",
        curveIntensity: -0.05,
        connectFrom: "bottom",
        shiftFrom: -0.6,
        connectTo: "top",
        shiftTo: -10,
        lineWidth: 2,
    },
    {
        source: "moral_reasoning",
        target: "game",
        curveIntensity: -0.06,
        connectFrom: "bottom",
        shiftFrom: -1.1,
        connectTo: "top",
        shiftTo: -10,
        lineWidth: 2,
    },
    {
        source: "moral_reasoning",
        target: "shared_reading",
        curveIntensity: 0,
        connectFrom: "bottom",
        shiftFrom: 0,
        connectTo: "top",
        shiftTo: 0,
        lineWidth: 2,
    },
    {
        source: "construction",
        target: "attachment",
        curveIntensity: 0.05,
        connectFrom: "bottom",
        shiftFrom: -2,
        connectTo: "top",
        shiftTo: 0.6,
        lineWidth: 2,
    },
    {
        source: "experimentation",
        target: "attachment",
        curveIntensity: 0.07,
        connectFrom: "bottom",
        shiftFrom: 4,
        connectTo: "top",
        shiftTo: 1.1,
        lineWidth: 2,
    },
    {
        source: "storytelling",
        target: "attachment",
        curveIntensity: -0.05,
        connectFrom: "bottom",
        shiftFrom: 10,
        connectTo: "top",
        shiftTo: -0.6,
        lineWidth: 2,
    },
    {
        source: "game",
        target: "attachment",
        curveIntensity: -0.07,
        connectFrom: "bottom",
        shiftFrom: 2,
        connectTo: "top",
        shiftTo: -1.1,
        lineWidth: 2,
    },
    {
        source: "shared_reading",
        target: "attachment",
        curveIntensity: 0,
        connectFrom: "bottom",
        shiftFrom: 0,
        connectTo: "top",
        shiftTo: 0,
        lineWidth: 2,
    }
];

export const initialConfig = {
    curveIntensity: 0.5,
    lineWidth: 3,
    textOrientation: "horizontal",
};