<?php

// Course fields group
acf_add_local_field_group(array(
	'key' => 'group_course_fields',
	'title' => 'Поля курса',
	'fields' => array(
		array(
			'key' => 'field_course_description',
			'label' => 'Описание курса',
			'name' => 'course_description',
			'type' => 'textarea',
			'instructions' => 'Краткое описание курса для списка курсов',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
		),
		array(
			'key' => 'field_course_short_description',
			'label' => 'Краткое описание курса для баннера',
			'name' => 'course_short_description',
			'type' => 'textarea',
			'instructions' => 'Краткое описание курса для отображения на баннере',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => '',
		),
		array(
			'key' => 'field_course_access_link',
			'label' => 'Ссылка на курс',
			'name' => 'course_access_link',
			'type' => 'url',
			'instructions' => 'URL для получения доступа к курсу',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'https://example.com/course',
		),
		array(
			'key' => 'field_course_audience',
			'label' => 'Целевая аудитория',
			'name' => 'course_audience',
			'type' => 'checkbox',
			'instructions' => 'Выберите целевую аудиторию курса',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'parents' => 'Родителям',
				'teachers' => 'Педагогам',
			),
			'allow_custom' => 0,
			'default_value' => array(
			),
			'layout' => 'vertical',
			'toggle' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_course_duration',
			'label' => 'Длительность курса',
			'name' => 'course_duration',
			'type' => 'text',
			'instructions' => 'Укажите продолжительность курса (например: 4 недели)',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_course_level',
			'label' => 'Уровень сложности',
			'name' => 'course_level',
			'type' => 'select',
			'instructions' => 'Выберите уровень сложности курса',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'beginner' => 'Начальный',
				'intermediate' => 'Средний',
				'advanced' => 'Продвинутый',
			),
			'default_value' => false,
			'allow_null' => 1,
			'multiple' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'courses',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

?>