name: 🚀 Deploy WordPress Theme via FTP

on:
  push:
    branches: ["main", "dev"]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: 📦 Install LFTP
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: 🛠️ Update theme name in style.css
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            sed -i 's/Theme Name: childlab-react-test/Theme Name: childlab-react/' /home/runner/work/child-lab-test/child-lab-test/style.css
            echo "Theme name updated to childlab-react"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            sed -i 's/Theme Name: childlab-react-test/Theme Name: childlab-react-dev/' /home/runner/work/child-lab-test/child-lab-test/style.css
            echo "Theme name updated to childlab-react-dev"
          fi

      - name: 📤 Sync files to FTP server
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            lftp -e "
              set ftp:ssl-allow no;
              set ssl:verify-certificate no;
              open ${{ secrets.FTP_HOST }};
              user ${{ secrets.FTP_USERNAME }} '${{ secrets.FTP_PASSWORD }}';
              mirror --reverse --verbose --delete \
                     --ignore-time \
                     --exclude-glob .git/ \
                     --exclude-glob .github/ \
                     ./ ${{ secrets.REMOTE_PATH_MAIN }};
              bye;
            "
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            lftp -e "
              set ftp:ssl-allow no;
              set ssl:verify-certificate no;
              open ${{ secrets.FTP_HOST }};
              user ${{ secrets.FTP_USERNAME }} '${{ secrets.FTP_PASSWORD }}';
              mirror --reverse --verbose --delete \
                     --ignore-time \
                     --exclude-glob .git/ \
                     --exclude-glob .github/ \
                     ./ ${{ secrets.REMOTE_PATH_DEV }};
              bye;
            "
          fi
